# -*- coding: utf-8 -*-
"""toots-fediverse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1803o6fFyMYUKk2SJ_6ThGy65VQIlQKw8
"""

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import networkx as nx
import json
import requests

#import mastodon
#from mastodon import Mastodon
import time
from datetime import date

import requests
import pandas as pd

URL = "https://fediscience.org/api/v1/timelines/public"
access_token = '04weKMQmTLx2mFSlO8_6PBLGyOR7b2RuPTdQFEyENwg'
user_toots = []
date_limit = pd.Timestamp('2023-08-04T23:00:00.000Z', tz='utc')

if access_token:
    headers = {
        'Authorization': f'Bearer {access_token}'
    }
    max_id = None
    is_end = False

    while True:
        time.sleep(1)
        params = {}

        r = requests.get(URL, headers=headers, params=params)
        toots = json.loads(r.text)

        if len(toots) == 0:
                break
        if 'error' in toots:
                print( toots)
                break
        max_id = toots[-1]['id']
        params = {'limit': 40, 'max_id' : max_id}


        for t in toots:
          user_toots.append(t)
          timestamp = pd.Timestamp(t['created_at'])
                    #print(timestamp)
          if timestamp <= date_limit:
            is_end = True
            break

        if is_end is True:
          break


    df = pd.DataFrame(user_toots)

df = pd.DataFrame(user_toots)

print(max(list(df['created_at'])))

fediverse_tweets = df.to_csv('fediverse_tweets.csv')

